/**
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef KMSENGINE_BACKING_RSA_RSA_KEY_H_
#define KMSENGINE_BACKING_RSA_RSA_KEY_H_

#include <string>

#include "src/backing/client/digest_case.h"
#include "src/backing/status/status.h"
#include "src/backing/status/status_or.h"

namespace kmsengine {
namespace backing {

// Interface that mirrors a subset of the RSA_METHOD interface from OpenSSL,
// except with arguments swapped for types native to the engine.
//
// When `RSA` objects are generated by the engine, an `RsaKey` implementation
// containing a handle to the private key resource ID should be attached to the
// `RSA` object. Then, when the bridge layer's `RSA_METHOD` implementations are
// called, the bridge layer should retrieve the `RsaKey` attached to the calling
// `RSA` object.
//
// The bridge layer is also responsible for converting OpenSSL-native types from
// the `RSA_METHOD` arguments into engine-native types prior to calling the
// associated `RsaKey` methods. This is because some conversions require
// knowledge of symbols from the OpenSSL library (which is not available to the
// backing layer).
class RsaKey {
 public:
  virtual ~RsaKey() = default;

  // TODO(zesp): Investigate if these are necessary given Sign and Verify.
  // It may be sufficient for `PublicEncrypt` and `PublicDecrypt` to redirect
  // to `Sign` and `Verify`; it also may be impossible for them to be used
  // with the engine since the OpenSSL specification for `rsa_pub_enc` and
  // `rsa_pub_dec` does not guarantee that the input will be a valid digest
  // (in fact, the documentation suggests using these functions for signing
  // strings of arbitrary length without hashing).
  virtual StatusOr<std::string> PublicDecrypt(std::string message,
                                              int padding) = 0;
  virtual StatusOr<std::string> PrivateEncrypt(std::string message,
                                               int padding) = 0;

  // TODO(zesp): Currently out of scope for the engine (non-signing operations),
  // but revisit this.
  virtual StatusOr<std::string> PublicEncrypt(std::string message,
                                              int padding) = 0;
  virtual StatusOr<std::string> PrivateDecrypt(std::string message,
                                               int padding) = 0;

  // Signs `message_digest` using the underlying RSA private key. Returns the
  // resulting signature as a `std::string`, or an error `Status`.
  virtual StatusOr<std::string> Sign(DigestCase type,
                                     std::string message_digest) = 0;

  // Verifies that `signature` is a valid signature for `message_digest` given
  // the underlying RSA private key. Returns `Status::kOk` if the signature is
  // valid, or an error `Status`.
  virtual Status Verify(DigestCase type,
                        std::string message_digest,
                        std::string signature) = 0;
};

}  // namespace backing
}  // namespace kmsengine

#endif  // KMSENGINE_BACKING_RSA_RSA_KEY_H_
